dataset_name: shapenet
datadir: ./data/shapenet_simulator/random
expname: tensorf_shapenet_VM
basedir: ./log



n_voxel_init: 2097156 # 128**3
n_voxel_final: 27000000 # 300**3
upsamp_list: [2000,3000,4000,5500,7000]
update_alphamask_list: [2000,4000]
step_ratio: 0.5
n_samples: 1000
coarse_only: False

class_num: 7
feature_rgb: 128
feature_semantic: 128
data_dim_rgb: 27
data_dim_semantic: 27
n_lamb_sigma: [16, 16, 16]
n_lamb_sh: [48,48,48]
model_name: TensoRFSemantic
ndc_ray: False
alpha_mask_thre: 0.0001
density_shift: -10

shadingmode_rgb: SH
shadingmode_semantic: MLP
fea2dense_act: softplus

use_xyz: False
use_view: False
random_init: False
pos_pe: 2
view_pe: 2
fea_pe: 2

distance_scale: 10
ortho_weight: 0.0
l1_weight_init: 1.0e-4
l1_weight_rest: 5.0e-5
rm_weight_mask_thre: 1.0e-4
tv_weight_density: 0.0
tv_weight_rgb: 0.0
tv_weight_semantic: 0.01